### ISSUE TITLE
Xcode error when used in IB

### ISSUE THREAD

**Issue by danqing** [TimOliver/TORoundedButton#19]
<img width="706" alt="Screen Shot 2019-06-16 at 11 40 54 AM" src="https://user-images.githubusercontent.com/5134133/59558742-a94e8680-902b-11e9-8574-8ffa87a87ce4.png">
This is directly from the TORoundedButtonExample project.

**Comment by TimOliver** [comment]
Thanks for the report @danqing! I thought it was just me having this issue.

I discovered that it was the result of a collision of the framework name in the same build target. I renamed the internal name for the framework and this seems to have fixed it. Please pull the latest version. :)

**Comment by danqing** [comment]
Error is gone. Thanks!
