### ISSUE TITLE
Inactive when inside UICollectionViewCell

### ISSUE THREAD

**Issue by krzyzanowskim** [TimOliver/TORoundedButton#25]
I don't know what may be the cause yet, but what I see is that if I use RoundedButton (Swift)  inside `UICollectionViewCell` (added to `contentView`), it doesn't handle any action. If I switch to UIButton the same `addTarget:...` start working, this is why I suspect there is maybe something missing in this component.

I use RoundedButton in other places and it works just fine ;)

I really can't explain this behavior more at this point, I'm sorry.

**Comment by TimOliver** [comment]
Hey @krzyzanowskim!

Hmm. Really? I just tested it in a sample app, and it seems to be working fine for me. You do need to disable `delaysContentTouches` for the effect to played, but the event still fires.

I wonder if there is some kind of touch responder chain issue you're having. In any case, `RoundedButton` and `UIButton` both derive the same tap logic from `UIControl`, so unless `UIButton` is doing something extra internally, they *should* be the same.

I've attached my sample app. Can you have a look at it and see if there's anything different with your collection view set up?

Thanks!

[RoundedButtonTest.zip](https://github.com/TimOliver/TORoundedButton/files/3438145/RoundedButtonTest.zip)

**Comment by krzyzanowskim** [comment]
right. It may be something with the https://github.com/MessageKit/MessageKit I'm dealing with, that is built on top of UICollectionView, and I assumed It's the same. I tried `delaysContentTouches` there.
But then the fact `UIButton` worked (I just replaced it in the same place) got me off the hook.
