### ISSUE TITLE
Add Package.swift for SPM support

### ISSUE THREAD

**Issue by simone-gasparini** [TimOliver/TORoundedButton#26]
Please consider add Package.swift for Swift Package Manager support

**Comment by TimOliver** [comment]
Thanks for the suggestion @simone-gasparini!

I've already tried and failed hopelessly at adding SPM support to [one of my other libraries](https://github.com/TimOliver/TOSegmentedControl/issues/3]. I need to spend a lot of time actually learning how to use it properly, but I don't have the free time right now.

Any help would be very much appreciated here. :)

**Comment by simone-gasparini** [comment]
Added pull request #27

**Comment by TimOliver** [comment]
Thanks again for all your hard work in making that happen @simone-gasparini! If you're ever in Tokyo, let me buy you a drink. :)

**Comment by simone-gasparini** [comment]
@TimOliver you're welcome and thank you for you awesome job! Hopefully one day!!! 😄
