### ISSUE TITLE
Are you interested in a Swift port of this button?

### ISSUE THREAD

**Issue by psalzAppDev** [TimOliver/TORoundedButton#36]
Hi @TimOliver 

I love your simple, but powerful implementation of this kind of button - exactly what I need for my apps.
I ported this library to Swift 5 - along with the unit tests and the sample app. 

If you are interested, I could add you as a collaborator to my private repo, you could have a look, and if you like it, maybe you'd like to release it alongside your Objective-C implementation.

Cheers,
Peter

**Comment by TimOliver** [comment]
Hi Peter!

Thank you so much! I'm glad you liked this library!

Woah! You rewrote the whole thing in Swift? Amazing! Sure! I'd be happy to check it out as a private collaborator.

I couldn't possibly take it and add it here. That would be taking credit for your work. I think you should make it a standalone repo. I'd be happy to add a link to it from this repo. :)

**Comment by psalzAppDev** [comment]
Thanks! I don't mind hosting the library myself, makes maintaining easier. Will do some refinements (Swift package, project organization, readme file etc) and then it is ready for release.

**Comment by TimOliver** [comment]
Hope the release went well Peter! 🙏
